CC=g++

CFLAGS=-Wall -std=c++11

one.o: one.cpp
	$(CC) $(CFLAGS) one.cpp -o one && ./one
factors.o: factors_of_a_number.cpp
	$(CC) $(CFLAGS) factors_of_a_number.cpp -o one && ./one
detect_prime_1.o: detect_prime_1.cpp
	$(CC) $(CFLAGS) detect_prime_1.cpp -o one && ./one
digits_of_a_number.o: digits_of_a_number.cpp
	$(CC) $(CFLAGS) digits_of_a_number.cpp -o one && ./one
reverse_num.o: reverse_num.cpp
	$(CC) $(CFLAGS) reverse_num.cpp -o one && ./one
gcd.o: gcd.cpp
	$(CC) $(CFLAGS) gcd.cpp -o one && ./one
triangle-left-1.o: triangle-left-1.cpp
	$(CC) $(CFLAGS) triangle-left-1.cpp -o one && ./one
triangle-down-1.o: triangle-down-1.cpp
	$(CC) $(CFLAGS) triangle-down-1.cpp -o one && ./one
clear:
	rm -rf one *.o