CC=g++

CFLAGS=-Wall -std=c++11

one.o: one.cpp
	$(CC) $(CFLAGS) one.cpp -o one && ./one
factors.o: factors_of_a_number.cpp
	$(CC) $(CFLAGS) factors_of_a_number.cpp -o one && ./one
clear:
	rm -rf one *.o